# Generated by Django 3.1 on 2021-07-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateTimeField(auto_now_add=True)),
                ('csv_lines', models.IntegerField(default=0, verbose_name='Lines')),
                ('csv_size_in_kb', models.FloatField(default=0, verbose_name='Size (KB)')),
                ('txt_lines', models.IntegerField(default=0, verbose_name='Lines')),
                ('txt_size_in_kb', models.FloatField(default=0, verbose_name='Size (KB)')),
            ],
        ),
    ]
